version: "2"

linters:
  settings:
    errcheck:
      # https://github.com/hashicorp/terraform-provider-aws/blob/9c9a116a857fb838a0e7d1cfbf420c2524f0abe1/.golangci.yml#L37-L39
      exclude-functions: 
        - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
        - io.Close



run:
  timeout: 10m
