version: 2
builds:
  - id: "normal-build"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}"

  # Darwin build (CGO enabled, fsnotify tag)
  - id: "darwin-build"
    env:
      - CGO_ENABLED=1
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - fsnotify
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
  - formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  disable: true
changelog:
  disable: true
