# Configuration for markdownlint
# https://github.com/DavidAnson/markdownlint#configuration

default: true

# Disabled Rules
# https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

MD001: false
MD004: false
MD007: false
MD009: false
MD010: false
MD012: false
MD013: false
MD014: false
MD022: false
MD031: false
MD033: false
MD034: false
MD047: false
