## These checks will be superseded by documentation.yml
## when the provider documentation layout is moved to
## the Terraform Registry layout.
name: Website Checks
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/website.yaml
      - website/docs/**
      - .markdownlint.yml

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avto-dev/markdown-lint@v1
        with:
          args: 'website/docs'
          config: '.markdownlint.yml'
