## These checks will be superseded by documentation.yml
## when the provider documentation layout is moved to
## the Terraform Registry layout.
name: Website Checks
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/website-link.yaml
      - docs/**
      - .markdownlint.yml

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        name: markdown-link-check docs/**/*.md
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdownlinkcheck.json'
          folder-path: 'docs'
          file-extension: '.md'